/**
 * Все тексты интерфейса живут здесь. Ни одной строки в компонентах —
 * иначе добавить казахский потом будет дороже, чем сделать это сразу.
 */
export const ru = {
  app: { name: 'Хата' },

  nav: { money: 'Закуп', things: 'Вещи', chores: 'Дежурства' },

  join: {
    title: 'Заходи в квартиру',
    codeLabel: 'Код квартиры',
    codePlaceholder: 'например, ALMATY-42',
    enter: 'Войти',
    whoAreYou: 'Кто ты?',
    notListed: 'Меня тут нет',
    addMe: 'Добавить себя',
    yourName: 'Как тебя зовут',
    createTitle: 'Новая квартира',
    createName: 'Название квартиры',
    createCta: 'Создать',
    orCreate: 'или создать новую',
    badCode: 'Такой квартиры нет. Проверь код.',
    nameTaken: 'Такое имя тут уже есть',
    emptyName: 'Впиши имя',
  },

  money: {
    title: 'Закуп',
    balanceZero: 'Все в расчёте',
    owesYou: 'должен тебе',
    youOwe: 'ты должен',
    settleUp: 'Рассчитаться',
    settleHint: 'Меньше переводов не получится — считал по минимуму',
    markSettled: 'Отметить перевод',
    addPurchase: 'Записать трату',
    amount: 'Сколько',
    who: 'Кто платил',
    participants: 'На кого делим',
    note: 'На что',
    date: 'Когда',
    save: 'Записать',
    cancel: 'Отмена',
    everyone: 'Все',
    paidBy: 'платил',
    perPerson: 'по',
    empty: 'Пока ничего не записано. Первый закуп — и балансы поедут.',
    needParticipants: 'Отметь хотя бы одного',
    needAmount: 'Впиши сумму',
    settlement: 'перевод',
    history: 'История',
    showMore: 'Показать ещё',
  },

  things: {
    title: 'Вещи',
    needCheck: 'Надо пересчитать',
    needCheckHint: 'Система спрашивает не каждый день, а когда подходит срок',
    runningOut: 'Скоро кончится',
    all: 'Все вещи',
    shared: 'Общие',
    mine: 'Мои',
    add: 'Добавить вещь',
    name: 'Что это',
    unit: 'В чём считаем',
    interval: 'Через сколько дней пересчитать в первый раз',
    intervalHint: 'После первого пересчёта система сама подберёт срок',
    owner: 'Чья вещь',
    sharedOption: 'Общая',
    photo: 'Фото',
    takePhoto: 'Снять или выбрать',
    removingBg: 'Убираю фон…',
    bought: 'Купили',
    boughtQty: 'Сколько взяли',
    check: 'Пересчитать',
    checkQty: 'Сколько осталось',
    left: 'осталось',
    perDay: 'в день',
    daysLeft: 'хватит на',
    days: 'дн.',
    runsOut: 'кончится',
    unknownRate: 'расход пока неизвестен',
    roughRate: 'расход прикидочный',
    checkedNever: 'ни разу не считали',
    nextCheck: 'следующий пересчёт',
    unlogged: 'Похоже, закупку не записали — один замер выкинул',
    empty: 'Вещей пока нет. Добавь то, что реально кончается и бесит.',
    archive: 'Убрать из списка',
    checkShort: 'пересчитать',
    buyShort: 'кончается',
    replacePhoto: 'Заменить фото',
    bgFailed: 'Фон убрать не вышло — оставил фото как есть',
    photoFailed: 'С этим файлом не получилось. Попробуй другое фото.',
    shelf: 'Полка',
  },

  chores: {
    title: 'Дежурства',
    yourTurn: 'Твоя очередь',
    turnOf: 'очередь',
    done: 'Сделал',
    add: 'Добавить дежурство',
    name: 'Что делаем',
    period: 'Как часто, дней',
    order: 'Очередь',
    daysSince: 'дней назад',
    neverDone: 'ещё ни разу',
    tally: 'Кто сколько раз',
    times: 'раз',
    empty: 'Дежурств нет. Добавь то, из-за чего реально спорите.',
    days: 'дн.',
    remove: 'Убрать дежурство',
    dueToday: 'сегодня',
    dueIn: 'через',
    overdueBy: 'срок прошёл',
  },

  common: {
    you: 'ты',
    save: 'Сохранить',
    cancel: 'Отмена',
    delete: 'Удалить',
    loading: 'Загружаю…',
    error: 'Что-то пошло не так',
    leave: 'Выйти',
  },
} as const;

export type Strings = typeof ru;
export const t = ru;
